### PR TITLE
Downgrade gsl-lite version for compatibility with Hera

### LINKED ISSUE #152: Downgrade gsl-lite version?
Hera's Intel compilers complain about gsl-lite versions 0.35 - 0.37. Downgrading to 0.34 works fine. I would rather not debug the issue now due to time constraints.

Two options here:
- update the global stack to set 0.34 as the version for gsl-lite (#153), or
- use the older version only on Hera.

For other HPCs, you can check for the gsl-lite version issue by building ioda-engines PR JCSDA/ioda-engines/pull/134.

### PR DESCRIPTION
**Pull request by rhoneyager**
Hera's Intel compilers complain about gsl-lite versions 0.35 - 0.37.

Potentially fixes #152.

### CODE REVIEW

**Review by mmiesch — APPROVED** [review]
I'm ok either way

**Review by srherbener — APPROVED** [review]
I had to shut off the build of the test programs since they would not compile on my Mac. This should be okay since we are not running the tests in this flow and only installing the header-only package.

After building and installing gsl_lite on my Mac, I tested ioda-engines using the `feature/gsl-external-library` branch (which runs find_package to access gsl-lite) and ioda-engines built properly and all tests passed.

Perhaps we should test again on Hera?

**Comment by mmiesch** [comment]
@rhoneyager - are you ready to merge this?  Hera is happy?  If she's not, I know she can get pretty nasty (just ask any of Zeus's consorts!)

**Comment by rhoneyager** [comment]
Working on Hera

**Pull request merged**
