### PR TITLE
Feature/hpc updates

### PR DESCRIPTION
**Pull request by mmiesch**
As requested by some, this provides some guidance for building jedi-stack modules on S4, Discover, and Cheyenne.

There are now config scripts for all three machines.  I also added a Cheyenne toolchain, which I will include in a jedi-cmake PR to follow this one.

Perhaps more importantly, there is now much expanded documentation.  It is not intended to be comprehensive.  I don't think building modules on HPC systems will ever be just plu-and-play - it requires a little effort by the developer to adapt to problems that can arise.  Documenting every one of the possibilites in detail would be unsustainable.  This is a bit of a compromise, offered as tips rather than detailed step-by-step instructions, which would become out of date when something gets updated.

Due to the length, I separated these out into a separate docs directory.

The tips also include a discussion of how to build with c++14 using intel compilers on hpc systems - somthing that may be useful for @rhoneyager and @rickgrubin for Orion and Hera

### CODE REVIEW

**Comment by markjolah** [comment]
Awesome.  A quick look over things looks fine.  I will attempt to build on a few machines.

**Comment by mmiesch** [comment]
I just made two rather significant changes

1. I added a script to build git-lfs (needed for Orion and Discover)
2. I split up the config files, extracting the bit where you specify the stack components and putting it in a new script called `choose_modules`

The motivation for 2. was to not make it necessary to add a `STACK_BUILD_X` line to a dozen or more files every time a new script is added for package X.   However, since the container builds are automated, this is only called if the MODULES flag is false.  So, we can still hardwire in what goes in the containers.

**Comment by markjolah** [comment]
I like the reduction in boilerplate necessary to add/remove a package with the new `choose_modules.sh`.  It's not always clear which modules I will need to choose for each system.   I had to look at your S4 modules to get the list of requirements.  I'm not sure I have a better suggestion yet, still thinking about it.

I have a few minor bugfixes/question for the S4 setup should I submit a PR against this one?

**Comment by mmiesch** [comment]
> I have a few minor bugfixes/question for the S4 setup should I submit a PR against this one?

Sure - or just comment on the lines you'd like to change

**Comment by markjolah** [comment]
Ok. One more question about the `modulefules/apps/jedi/intel-impi.lua`.  I just noticed this has the versions hardcoded which is now going to be wrong for a few of the packages, bufrlib, eigen, anything else we might have recently changed?   I was forgetting to update here when I changed a version number in build_stack.sh.  For example the clang-mpich.lua and clang-openmpi.lua don't have version numbers.  I also set it up that way for the "gentoo" version of this file, so that I don't have to remember update the version numbers.    Could we do the same with the intel-impi.lua?

**Comment by mmiesch** [comment]
Yes - that is out of date.  I don't use any of the files in the apps directory.  I typically just manually create these meta-modules for the system.  We could put one in for each system but I'm afraid they would take a lot of effort to maintain.  Basically, this is just a laundry list for whatever modules you just installed so it not always going to be the same.

**Comment by mmiesch** [comment]
Also - sometimes the version numbers are useful to distinguish jedi-built modules from native modules with the same name.  I fie the intel-impi.lua file just as really an example

**Comment by markjolah** [comment]
OK.  I figured you must have been customizing those top level `apps` modules anyways, or we would have noticed the problems already.  I'm not sure I have a better solution yet, just curious how it works.

**Comment by mmiesch** [comment]
Yea, I'm open to suggestions but we maintain over a dozen modules on various systems.  If we had to do a feature branch, PR, and code reviews every time we changed one of those it would be a waste of everyone's time.   If someone is gone and someone else needs to generate a stack, I think the best approach is just to log on to the system and start from the meta-module file that is actually in circulation.

**Pull request merged**
