### PR TITLE
Feature/cgal

### PR DESCRIPTION
**Pull request by mmiesch**
This adds the CGAL library to the jedi-stack.  CGAL is used by Atlas for Delaunay triangulation when constructing a mesh (inter-node communication infrastructure) for unstructured grids.  For now it will probably be an optional addition to the stack but it may become a required dependency.

### CODE REVIEW

**Comment by MarekWlasak** [comment]
Have you looked at the licensing issues associated with CGAL? Some of it is under LGPL  and the rest is under a GPL license.  @DJDavies2 will be building it from source here at UKMO, so we will be o.k. But is this an issue if you put it on the stack?

**Comment by aerorahul** [comment]
@MarekWlasak I don't see why this causes a licensing issue.  The stack simply downloads the publicly available source code, and builds it as per the instructions provided in the source code.

**Comment by MarekWlasak** [comment]
@aerorahul - I am not a legal expert but I thought simply that the problem is with distribution i.e. if this stack is distributed then it would break the terms of the GPL licence.  What is the difference between this and building fftw?

**Comment by aerorahul** [comment]
@MarekWlasak I am not a legal expert either. Are we distributing the `cgal` package? I don't think we are. We are distributing the `jedi-stack`. The `stack` does not contain the package.  The `stack` contains a script obtains the package from the public source, builds it as is, and uses it in the application (`atlas`). `FFTW` also has a GPL. 

I saw this PR was getting stale, so took a look and found your question.

**Comment by mmiesch** [comment]
I agree with @aerorahul - we're not actually distributing it.   The script just grabs it from the public distribution.  So, I don't think there's a licensing issue.  The reason this is languishing is because, as I have mentioned elsewhere, this re-introduces boost as a dependency.   Though CGAL itself is headers-only, it requires these:
~~~~~
boost_thread
boost_system
~~~~~
But, if you install these, then everything works (I think - need to check again).  So, it's still worth adding this as an option but we shouldn't make it a requirement.

**Comment by mmiesch** [comment]
Ok - the good news is that I think this branch works and is ready to merge.  After installing boost on my Mac, I was able to install CGAL and ecbuild was able to find it.  The bad news is that it caused a build error in atlas:
~~~~~
-- Found package CGAL required for feature TESSELATION
-- Found package Boost required for feature TESSELATION
-- Feature TESSELATION enabled
CMake Error at atlas/CMakeLists.txt:141 (set_target_properties):
  set_target_properties can not be used on an ALIAS target.
~~~~~
But, I think this is an atlas problem, not a jedi-stack problem

**Comment by ytremolet** [comment]
@mmiesch the problem has been fixed in the develop branch of the ecmwf repo. Can you try the branch develop-jcsda of the ecmwf repo? It is based on the latest ecmwf develop and works for me in the fv3 bundle.

**Comment by mmiesch** [comment]
Thanks @ytremolet - yes, this fixes the problem on my Mac

**Comment by mmiesch** [comment]
This PR and branch is pretty stale - we should either merge it or delete it.  I would lean toward merging.  The problem with it has always been that installing CGAL requires a few boost libraries, so it re-introduces boost as a dependency.  This is what they actually say about it:

> CGAL only requires the headers of the Boost libraries, but some demos and examples depend on the binary library Boost.Program_options. As an exception and because of a bug in the GCC compiler about the C++ 11 keyword thread_local, the CGAL_Core library always requires the binary library Boost.Thread if the GCC compiler version 9.0 or earlier is used.

So, if you use gcc > 9 or another compiler like intel or clang to build, then you may not need to install any boost binaries.  This works on my Mac using gnu 9.2, though I do also have the boost libraries installed via brew.

So, I think we can merge this PR to provide an optional extension.  We may make use of it in the future with atlas - for example, as an optional way to create a Delaunay mesh for use with unstructured grid interpolation and partitioning.

**Comment by mmiesch** [comment]
GitHub seems very confused about this branch.  This PR says 108 files changed but when I compare branches directly it says 12 files changed.  I'm going to try to close and reopen.

**Pull request closed without merging**
