### PR TITLE
added option to built jcsda fork of ecbuild

### PR DESCRIPTION
**Pull request by mmiesch**
For those of you using jedi-stack - this adds the capability to switch between the jcsda fork of ecbuild and the ecmwf releases or develop branch, for testing.

### CODE REVIEW

**Comment by markjolah** [comment]
Looks good to me.  I think we may eventually need to switch to using a 'stable' branch on our ecbuild fork, as tracking the ecbuild 'master' or 'develop' too closely may lead to problems for us.  Assuming the version tag can be replaced with a branch name in the scripts here I think this will work when we get to that point.

**Comment by markjolah** [comment]
Also it appears I can't "approve" your PR even if I'm a selected reviewer since maybe I don't have proper permissions?

**Comment by aerorahul** [comment]
@mmiesch Is this ready to be merged?

**Comment by mmiesch** [comment]
@markjolah - strange - as a jedi core team member, you should already have access to this repo.  And, as far as I know, you should only need read permission to approve via a review.   We can sort it out next week when we return to Boulder.

**Pull request merged**
