### PR TITLE
Issue #148: load cmake module prior to building eigen module

### LINKED ISSUE #148: Load cmake module prior to building eigen module
The eigen module interface libraries for jedi-stack (currently used version: 3.3.7) requires at least cmake version 3.0 (see: https://gitlab.com/libeigen/eigen/-/blob/3.3.7/CMakeLists.txt#L533) in order to properly create Eigen targets in the Eigen3 namespace (see: https://gitlab.com/libeigen/eigen/-/blob/3.3.7/CMakeLists.txt#L568-575).

This requires the jedi-stack build script for the eigen module to load a sufficiently versioned cmake module prior to building.

### PR DESCRIPTION
**Pull request by rickgrubin**
## Description

The eigen module interface libraries for `jedi-stack` (currently used version: 3.3.7) requires at least `cmake` version 3.0 (see: https://gitlab.com/libeigen/eigen/-/blob/3.3.7/CMakeLists.txt#L533) in order to properly create Eigen targets in the Eigen3 namespace (see: https://gitlab.com/libeigen/eigen/-/blob/3.3.7/CMakeLists.txt#L568-575).

This requires the `jedi-stack` build script for the eigen module to load a sufficiently versioned `cmake` module prior to building.

This was first noted on Orion.

Added: other library scripts for which the module build configuration requires `cmake`.

### Issue(s) addressed

- fixes #148

## Dependencies

N/A

## Impact

No required changes in other repositories.

### CODE REVIEW

**Review by mmiesch — APPROVED** [review]
Looks good - did you say you were going to add this to other scripts as well or do the others that need it already have it?

**Comment by rickgrubin** [comment]
> Looks good - did you say you were going to add this to other scripts as well or do the others that need it already have it?

This code snippet is present in some, but not all, of the `buildscripts/libs/build_<stack_module>.sh` scripts. It's not clear to me which stack modules are wholly dependent on loading the appropriate `cmake` module. 

I would argue that it's not harmful to add it to all build scripts, and may preclude problems in the future. That said, it seems that problem hasn't been seen prior and elsewhere.

I can modify this PR to do add it in all build scripts if that's desired.

**Comment by mmiesch** [comment]
I think adding it where it's not needed is a bit confusing.  I think these are the only files that need it - anything that uses cmake or ecbuild:

```
(base) ✔ ~/JEDI/code/local_copy/jedi-stack/buildscripts/libs [feature/json-schema-validator|✔] 
16:43 $ grep -rl cmake *
build_bufrlib.sh
build_cgal.sh
build_cmake.sh
build_ecbuild.sh
build_eccodes.sh
build_eckit.sh
build_eigen.sh
build_geos.sh
build_gptl.sh
build_gsl_lite.sh
build_jasper.sh
build_jpeg.sh
build_json-schema-validator.sh
build_json.sh
build_lapack.sh
build_pio.sh
build_png.sh
build_proj.sh
build_pybind11.sh
(base) ✔ ~/JEDI/code/local_copy/jedi-stack/buildscripts/libs [feature/json-schema-validator|✔] 
16:43 $ grep -rl ecbuild *
build_atlas.sh
build_ecbuild.sh
build_eckit.sh
build_fckit.sh
build_odc.sh
```

So, I'd just make sure it's in those.

**Comment by mmiesch** [comment]
Thanks @rickgrubin - I second my initial approval!

**Comment by rickgrubin** [comment]
Added `module try-load cmake` where appropriate per previous comment from @mmiesch

**Review by markjolah — APPROVED** [review]
Awesome thanks for fixing all the future problems too.

**Pull request merged**
